/* global __dirname */
/* generated by unstuck-webpack */

var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var dir_js = path.resolve(__dirname, 'app');
var dir_css = path.resolve(__dirname, 'css');
var dir_build = path.resolve(__dirname, 'dist');

module.exports = {
    entry: {
      app : path.resolve(__dirname, 'index.js'),
      vendor : []
    },
    output: {
        path: dir_build,
        filename: 'bundle.js'
    },
    resolve: {
       modulesDirectories: ['node_modules', dir_js],
    },
    devServer: {
        contentBase: dir_build,
    },
    postcss: function () {
        return [require('autoprefixer')];
    }, 
    devtool: 'source-map',
    stats: {
        colors: true,
        chunkModules: false
    },
    plugins: [
        new ExtractTextPlugin("[name].css", {  allChunks: true }), 
        new webpack.optimize.CommonsChunkPlugin("vendor", "[name].js"),
        new webpack.NoErrorsPlugin()
    ],

    module: {
        loaders: [
            {
                loader: 'file?name=assets[name].[ext]',
                test: /\.png($|\?)|\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/
            },
            {
                loader: 'babel-loader',
                test: /\.js($|\?)|\.jsx($|\?)/,
                exclude: /node_modules/,
                presets : ['es2015', 'react']
            },
            {
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!postcss-loader!sass-loader?sourceMap'),
                test: /\.sass$/
            }
        ],
        preLoaders: [
          {
            test: /\.js($|\?)|\.jsx($|\?)/,
            loaders: ['eslint'],
            exclude : [/node_modules/]
          }
        ]
    }
}
