# Generated by Django 2.0.7 on 2018-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.PositiveIntegerField(blank=True, max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Service', models.CharField(blank=True, choices=[('DEV', 'Web Development'), ('IT', 'IT & Networking'), ('SERVERS', 'Servers, Cloud, Linux, etc.'), ('PHOTO', 'Photography'), ('VIDEO', 'Video')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Message', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
