# Generated by Django 2.0.7 on 2018-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wattup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
