# Generated by Django 2.0.7 on 2018-08-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wattup', '0002_auto_20180805_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['date'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
